[build]
  publish = "public"
  command = "npm run shipit"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  GO_IMPORT_PATH = "github.com/yurm04/yuraima.com"
